"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config
import cloudinary
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY =config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG =config("DEBUG",default=True,cast=bool)

ALLOWED_HOSTS =config("ALLOWED_HOST").split(",")

CORS_ALLOWED_ORIGINS=config("CORS_ALLOWED_ORIGINS").split(",")

CORS_ALLOW_CREDENTIALS=True

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'daphne',
    'cloudinary',
    'cloudinary_storage',
    'rest_framework',
    'django_extensions',
    'channels',
    'chat',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION='core.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME':config('POSTGRES_DB'),
        'USER':config('POSTGRES_USER'),
        'PASSWORD':config('POSTGRES_PASSWORD'),
        'HOST':config('HOST')
    } if DEBUG else dj_database_url.parse(config('DATABASE_URL'))
}

AUTH_USER_MODEL='chat.User'

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT=BASE_DIR/"staticfiles"

STATICFILES_STORAGE='whitenoise.storage.CompressedManifestStaticFilesStorage'

AUTHENTICATION_BACKENDS=[
    'chat.customAuthentication.CustomBackendAuthentication','django.contrib.auth.backends.ModelBackend'
]

REST_FRAMEWORK={
    'DEFAULT_AUTHENTICATION_CLASSES':(
        # 'rest_framework.authentication.TokenAuthentication',
        'chat.customAuthentication.CustomJwtAuthentication',
    )
}
# LOGGING={
#     'version':1,
#     'handlers':{
#         'console':{
#             'class':'logging.StreamHandler'
#         },
#     },
#     'loggers':{
#         'django.db.backends':{
#             'handlers':['console'],
#             'level':'DEBUG'
#         }
#     }
# }

CHANNEL_LAYERS={
    'default':{
        'BACKEND':'channels_redis.core.RedisChannelLayer',
        'CONFIG':{
            'hosts':[config('REDIS_URL')]
        }
    }
}

cloudinary.config(
cloud_name=config('CLOUD_NAME'),
api_key=config('CLOUDINARY_KEY'),
api_secret=config('CLOUDINARY_SECRET'),
secure=True)

DEFAULT_FILE_STORAGE='cloudinary_storage.storage.MediaCloudinaryStorage'
MEDIA_URL='/media/'
MEDIA_ROOT=BASE_DIR / 'media'

EMAIL_BACKEND='django.core.mail.backends.console.EmailBackend'

CACHES={
    'default':{
        'BACKEND':'django_redis.cache.RedisCache',
        'LOCATION':config('REDIS_URL_OTHER')
    }
}

DATA_UPLOAD_MAX_MEMORY_SIZE=104857600
FILE_UPLOAD_MAX_MEMORY_SIZE=104857600

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
