# Generated by Django 6.0.1 on 2026-01-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='connectionrequest',
            name='unique_request_connection',
        ),
        migrations.RenameField(
            model_name='connectionrequest',
            old_name='auth_user',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='connectionrequest',
            old_name='other_auth_user',
            new_name='to_user',
        ),
        migrations.AddConstraint(
            model_name='connectionrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('from_user', 'to_user'), name='unique_request_connection'),
        ),
    ]
