# Generated by Django 6.0.1 on 2026-02-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_user_usermodel_usernam_bcd653_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='user',
        ),
        migrations.AddField(
            model_name='conversation',
            name='chat_type',
            field=models.CharField(blank=True, choices=[('group', 'Group'), ('direct', 'Direct')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
