# Generated by Django 6.0.1 on 2026-02-02 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_conversation_user_conversation_chat_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='participant',
            new_name='participants',
        ),
    ]
