# Generated by Django 6.0.1 on 2026-02-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_participant_conversation_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Conversation',
            new_name='conversation',
        ),
    ]
