# Generated by Django 6.0.1 on 2026-02-10 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_rename_conversation_message_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereciept',
            name='conversation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='mssgconversation_reciept', to='chat.conversation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messagereciept',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermessage_reciept', to=settings.AUTH_USER_MODEL),
        ),
    ]
