# Generated by Django 6.0.1 on 2026-02-12 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_conversation_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='super_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='super_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
