# Generated by Django 6.0.1 on 2026-02-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_conversation_super_admin'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messagereaction',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='messagereaction',
            constraint=models.UniqueConstraint(fields=('user', 'message', 'reaction'), name='unique_reaction'),
        ),
    ]
