# Generated by Django 6.0.1 on 2026-02-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_alter_messagereaction_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='messagereaction',
            name='unique_reaction',
        ),
        migrations.AddConstraint(
            model_name='messagereaction',
            constraint=models.UniqueConstraint(fields=('user', 'message'), name='unique_reaction'),
        ),
    ]
