# Generated by Django 6.0.1 on 2026-02-14 12:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_messagereaction_unique_reaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='attachment'),
        ),
    ]
