# Generated by Django 6.0.1 on 2026-02-24 07:35

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_alter_message_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='group_img',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='group_img'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_bg_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='bg-pictures'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_picture'),
        ),
    ]
