# Generated by Django 6.0.1 on 2026-03-03 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_remove_message_attachment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='prodile_picture',
            new_name='profile_picture',
        ),
    ]
