# Generated by Django 6.0.1 on 2026-03-15 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_rename_prodile_picture_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_chat/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'svg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='messagereciept',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('read', 'Read'), ('active', 'Active')], max_length=200),
        ),
    ]
