# Generated by Django 6.0.1 on 2026-03-20 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_alter_message_image_alter_messagereciept_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagereaction',
            name='Conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_reaction', to='chat.conversation'),
        ),
        migrations.AlterField(
            model_name='messagereaction',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='messagereciept',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('read', 'Read'), ('inactive', 'Inactive')], max_length=200),
        ),
    ]
