# Generated by Django 6.0.1 on 2026-03-20 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_messagereaction_conversation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagereaction',
            old_name='Conversation',
            new_name='conversation',
        ),
    ]
