# Generated by Django 6.0.1 on 2026-04-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_rename_conversation_messagereaction_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='pending_user',
            field=models.JSONField(default=list),
        ),
    ]
