# Generated by Django 6.0.4 on 2026-04-23 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_remove_message_audio_remove_message_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='attachement_type',
            new_name='attachment_type',
        ),
    ]
