# Generated by Django 6.0.4 on 2026-04-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_alter_message_attachment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='text',
        ),
        migrations.AddField(
            model_name='message',
            name='clientId',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
