# Generated by Django 6.0.4 on 2026-04-29 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_rename_content_message_text_message_clientid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='clientId',
            new_name='client_id',
        ),
    ]
