# Generated by Django 6.0.4 on 2026-05-02 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0024_rename_clientid_message_client_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagereciept',
            old_name='time_stamp',
            new_name='timestamp',
        ),
    ]
