# Generated by Django 6.0.4 on 2026-05-03 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_rename_time_stamp_messagereciept_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_read_msg_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lst_read_msg_id', to='chat.message'),
        ),
    ]
