# Generated by Django 6.0.4 on 2026-05-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0026_conversation_last_read_msg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_interaction',
            field=models.CharField(blank=True, default='text', max_length=200, null=True),
        ),
    ]
