# Generated by Django 6.0.4 on 2026-05-08 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_conversation_last_interaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='pending_user',
        ),
    ]
