# Generated by Django 6.0.4 on 2026-05-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_remove_conversation_pending_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='client_conversation_id',
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
    ]
